# Generated by Django 4.0.3 on 2022-03-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companies_price_to_earn_companies_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='raiting',
        ),
    ]
