# Generated by Django 4.0.3 on 2022-03-31 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_profile_tikers_tikers_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikers_profile',
            name='tikers',
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='change',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='price',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='price_to_earn',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='ticker',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='tikers_profile',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
