# Generated by Django 4.0.3 on 2022-03-31 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_companies_name_alter_goodcompanies_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('change', models.CharField(max_length=50)),
                ('price_to_earn', models.CharField(default='10', max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
